### ISSUE TITLE
Docker not working correctly

### ISSUE THREAD

**Issue by michaelrice** [cloudnull/cruton#2]
```
root@docker:/var/run/docker/libcontainerd/containerd# docker start -i pedantic_ride
Traceback (most recent call last):
  File "/usr/local/bin/cruton-manage", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/cruton/data_store/main.py", line 60, in main
    CONF(project='cruton')
  File "/usr/local/lib/python3.5/site-packages/oslo_config/cfg.py", line 2352, in __call__
    raise ConfigFilesNotFoundError(self._namespace._files_not_found)
oslo_config.cfg.ConfigFilesNotFoundError: Failed to find some config files: /etc/cruton/cruton.ini
```

Looks like the config is missing from the container build.

**Comment by devx** [comment]
Pull the latest code and do a build with no cache --no-cache.

```
docker build --no-cache -t cruton .
```

**Comment by michaelrice** [comment]
Hi @devx is something wrong with github? I checked a browser and the changes that were merged in #4  are not showing up. Next I did

```
root@docker:~/cruton# git remote show origin
* remote origin
  Fetch URL: https://github.com/cloudnull/cruton
  Push  URL: https://github.com/cloudnull/cruton
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

Then did:
```
root@docker:~/cruton# git pull origin master
From https://github.com/cloudnull/cruton
 * branch            master     -> FETCH_HEAD
Already up-to-date.
```

Then:

```
root@docker:~/cruton# git log|grep  f3b1489 
root@docker:~/cruton# head -n 1 Dockerfile 
FROM python:3.5.3-alpine
```

I dont know whats going on here but the change doesnt seem to be in master..

**Comment by cloudnull** [comment]
@michaelrice this just merged and should take care of the remaining issues https://github.com/cloudnull/cruton/pull/6. When you get a change it'd be great if you could rerun the test.

**Comment by michaelrice** [comment]
With the new README I was able to get this going. I have 1 suggestion for the Docker section though. I was running this on Ubuntu 16.10 which had `docker-compose  version (1.5.2-1)` but that was causing an error with the build 

    ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

I found I had to install docker-compose from pip so Im not sure what the minimum required version is but if you happen to know it might be worth mentioning in the README in the docker requirements section.
