### ISSUE TITLE
Keyspace does not exist

### ISSUE THREAD

**Issue by devx** [cloudnull/cruton#5]
When you run cruton for the first time it assumes that the keyspace already exists. It should create it ultimately there should be that initializes cassandra and setups the namespace, and tables.

```
cruton-manage --config-file /etc/cruton/cruton.ini sync_tables
Traceback (most recent call last):
  File "/usr/local/bin/cruton-manage", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/cruton/data_store/main.py", line 74, in main
    sync_data_store_cmd(keyspace=[data_store['keyspace']])
  File "/usr/local/lib/python2.7/site-packages/cruton/data_store/drivers/cassandra/models.py", line 131, in sync_tables
    keyspaces=keyspace
  File "/usr/local/lib/python2.7/site-packages/cassandra/cqlengine/management.py", line 190, in sync_table
    _sync_table(m, connection=connection)
  File "/usr/local/lib/python2.7/site-packages/cassandra/cqlengine/management.py", line 215, in _sync_table
    raise CQLEngineException(msg.format(ks_name, model))
cassandra.cqlengine.CQLEngineException: [Connection: DEFAULT_CONNECTION] Keyspace 'cruton' for model <class 'cassandra.cqlengine.models.Entities'> does not exist.
```

**Comment by devx** [comment]
Closing this as it's documented in the README.md file
